package: 
  name: test-osx-arm64
  version: 1

source:
  git_url: https://github.com/icl-utk-edu/heffte.git
  git_depth: 1

requirements:
  build:
    - cmake >=3.17.0
    - {{ compiler('cxx') }}
    - openmpi
  host:
    - openmpi
    - fftw
  run:
    - openmpi
    - fftw
