name: run-something

on:
  push

permissions:
  contents: read

jobs:
  test-run-thing:
    name: Install fierro-cpu from conda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,kwelsh-lanl,defaults
          auto-activate-base: false
      
      - name: create environment
        run: conda create -y --name fierro-env fierro-cpu
      
      - name: activate environment and test fierro
        run: |
          conda activate fierro-env
          which fierro
          fierro --help
